# Generated by Django 5.2.8 on 2025-12-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_user_alter_client_health_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='health_issues',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='client',
            name='wellness_goal',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
