# Generated by Django 5.2.8 on 2025-12-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_health_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='health_issues',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='client',
            name='wellness_goal',
            field=models.CharField(max_length=100),
        ),
    ]
