# Generated by Django 5.2.8 on 2025-12-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_health_issues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='health_issues',
        ),
        migrations.RemoveField(
            model_name='client',
            name='wellness_goal',
        ),
    ]
