# Generated by Django 5.2.8 on 2025-12-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_client_health_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='health_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='wellness_goal',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
