# Generated by Django 5.2.8 on 2025-11-15 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trainer_certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('training_field', models.CharField(max_length=100)),
                ('section_timing', models.CharField(choices=[('15', '15 min'), ('20', '20 min'), ('30', '30 min'), ('45', '45 min'), ('60', '60 min')], max_length=5)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('expecting_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_section', models.PositiveIntegerField()),
                ('adar_number', models.CharField(max_length=20)),
                ('adar_image', models.ImageField(upload_to='adhar_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('certificates', models.ManyToManyField(blank=True, to='trainer.trainercertificate')),
            ],
        ),
    ]
