# Generated by Django 5.2.8 on 2025-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainercertificate',
            name='image',
        ),
        migrations.AddField(
            model_name='trainercertificate',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
