# Generated by Django 5.2.8 on 2025-11-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_remove_trainercertificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='adar_image',
            field=models.URLField(max_length=500),
        ),
    ]
