# Generated by Django 5.2.8 on 2025-11-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_trainer_adar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
