# Generated by Django 5.2.8 on 2025-11-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_trainer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_profile/'),
        ),
    ]
