# Generated by Django 5.2.8 on 2025-11-18 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_upload_file'),
        ('trainer', '0005_trainer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='training_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='plan.plan'),
        ),
    ]
