# Generated by Django 5.2.8 on 2025-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_slotbooking_traineravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
