# Generated by Django 5.2.8 on 2025-11-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_trainer_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
