# Generated by Django 5.2.8 on 2025-11-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_alter_trainer_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='session_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='session_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
