# Generated by Django 5.2.8 on 2025-11-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_slotbooking_session_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
