# Generated by Django 5.2.8 on 2025-12-24 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_slotbooking_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('salary', models.DecimalField(decimal_places=2, help_text='Editable salary (auto-filled from trainer)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('hold', 'Hold')], default='pending', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trainer.trainer')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('trainer', 'year', 'month')},
            },
        ),
    ]
