# Generated by Django 5.2.8 on 2025-12-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_trainerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
