# Generated by Django 5.2.8 on 2025-12-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_alter_slotbooking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='session_start_apihit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
