# Generated by Django 5.2.8 on 2026-01-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_slotbooking_amount_paid_slotbooking_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
