# Generated by Django 5.2.8 on 2026-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0016_trainer_address_trainer_city_trainer_landmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
