# Generated by Django 5.2.8 on 2026-01-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0017_alter_slotbooking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpayment',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
