# Generated by Django 5.2.8 on 2026-01-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0020_trainer_couple_price_trainer_group_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('changed', 'Changed')], default='upcoming', max_length=20),
        ),
    ]
