# Generated by Django 5.2.8 on 2025-11-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_type', models.CharField(choices=[('3_days', '3 Days'), ('6_days', '6 Days')], max_length=20)),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('couple_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='plans/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
