# Generated by Django 5.2.8 on 2025-11-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='upload_file',
            field=models.ImageField(blank=True, null=True, upload_to='plans/images/'),
        ),
    ]
