
#  @base_url = http://178.248.112.16:9001/api/client/
 @base_url = http://localhost:8000/api/client/
POST http://178.248.112.16:9001/api/auth/login/
Content-Type: application/json

{
  "email_or_phno": "9976543210",
  "password": "Password@123"
}
### Client Registration
POST {{base_url}}register/
Content-Type: application/json

{
  "name": "Jesnajamal",
  "phno": "9170043210",
  "email": "jeznajamall@example.com",
  "dob": "2003-01-15",
  "gender": "female",
  "blood_group": "O+",
  "weight": "50.5",
  "height": "140.0",
  "address": "123 Street, City",
  "password":"Password@123",
  "health_issues": ["pcod", "backpain"],
  "wellness_goal": ["weight_loss", "improve_fitness"]
}
### List Clients
GET {{base_url}}?plan_id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NDgxMjA5LCJpYXQiOjE3NjU0MzgwMDksImp0aSI6IjcxY2M5MjE5ZTNlMzQ2YTk4YjM4YTY2OTYyZmI4NzBmIiwidXNlcl9pZCI6IjEifQ.AHCrKYu0iPJADB1tjdhA_AkZN7GjsYUV2ARtISk0Wl4
### Retrieve Client Profile
GET {{base_url}}4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTU5MzQwLCJpYXQiOjE3NjYxMTYxNDAsImp0aSI6Ijk5ZmEyODIyYjA0MTQ4NGZiM2I5NDczZDU1OWQwYWQyIiwidXNlcl9pZCI6IjEifQ.yEGtMZpZoDCl7cYNYHlfvKNBZcFRTnr8rY_Y2UEPhyQ
### Update Client Profile
PATCH {{base_url}}client/1/
Authorization: Bearer <access_token>
Content-Type: multipart/form-data

{
  "name": "John Updated",
  "weight": "72.0",
  "profile_pic": "@/path/to/new_image.jpg"
}
### Delete Client Profile
DELETE {{base_url}}client/1/
Authorization: Bearer <access_token>

###profile for mobile 
GET {{base_url}}profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDI3MDUwLCJpYXQiOjE3NjM5ODM4NTAsImp0aSI6IjIzMWU4Y2U5ZTM4MDRmOTlhOWYyN2E2NDAzNmVkNjU4IiwidXNlcl9pZCI6IjMifQ.TJax_-AIY0NJyG_FPL43A5xzsxXsCqmjvnM9RBtF_5s


###dashboard for web
GET {{base_url}}dashboard/counts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NDc5NDQ2LCJpYXQiOjE3NjU0MzYyNDYsImp0aSI6ImRkZTJkYTJlMmNmOTQ1YTlhNzZjMTEzYTc3ODI1MDg1IiwidXNlcl9pZCI6IjEifQ.-ZmKSMd-XvTQ3X00IvqFpS4sJz_2VYfNrLHk1sZY74w



