# @base_url = http://178.248.112.16:9001/api/plan/
@base_url = http://127.0.0.1:8000/api/plan/


### Create plan
POST {{base_url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDAzNjQyLCJpYXQiOjE3NjMzNjA0NDIsImp0aSI6ImU2MjYwNWE0Y2U1MjQ2ZGQ4Mjc1YTkzNjNjMjgxODkxIiwidXNlcl9pZCI6IjEifQ.KGmR_YxZG0t5szyU1LHuj-HOs_fNhyXgIxRDgd53sTI
Content-Type: application/json

{
"plan_name":"",
"plan_type":"",
"single_price":"",
"couple_price":"",
"group_price":"",
"description":"",
"upload_file":""
}

### List all plan
GET {{base_url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE2NTg3LCJpYXQiOjE3NjY0NzMzODcsImp0aSI6ImFmYzg0ZWI3YTBlYzRjMzM5OGMwNzU1MTRlOTlhMDQ3IiwidXNlcl9pZCI6IjEifQ.izn2zb4lLDLMxCGkDZheV_loURU14n0p_yLSFYeN_tM


### List all minplan
GET {{base_url}}miniplanlist/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1OTA5MTkwLCJpYXQiOjE3NjU4NjU5OTAsImp0aSI6IjNkYmNlZmFlNDc2MzQxZmZhYTNlNmE0OTI3OGIyMGI0IiwidXNlcl9pZCI6IjEifQ.xCp6Ot6IqiR65OnhAX67q4TYzkWvNC5Erwam_YSx7zw

### List all plan with pending trainer count
GET {{base_url}}pending-count/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE2NTg3LCJpYXQiOjE3NjY0NzMzODcsImp0aSI6ImFmYzg0ZWI3YTBlYzRjMzM5OGMwNzU1MTRlOTlhMDQ3IiwidXNlcl9pZCI6IjEifQ.izn2zb4lLDLMxCGkDZheV_loURU14n0p_yLSFYeN_tM



### detail view by id
GET {{base_url}}2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NDM0MzY2LCJpYXQiOjE3NjYzOTExNjYsImp0aSI6ImJlMDk1YzZiYzU5NTQ4NTQ4ODYxZTQ5NDA1ZTkwZGZkIiwidXNlcl9pZCI6IjEifQ.YdsPrbeaQhdsOiFph4pUR-bXid_LOEMs4G6ejYawNDU

### delete single plan
DELETE {{base_url}}2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NDMzODI0LCJpYXQiOjE3NjYzOTA2MjQsImp0aSI6IjViODM5YjBhMDgyOTQwZTY4ODFhMGE3MDdkNmM4ZGUyIiwidXNlcl9pZCI6IjEifQ.MnXCXjpTIQLkuy7P1t0A14qEBSIo6na6GzIbnjMET4A

### edit single plan
PUT {{base_url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDAzNjQyLCJpYXQiOjE3NjMzNjA0NDIsImp0aSI6ImU2MjYwNWE0Y2U1MjQ2ZGQ4Mjc1YTkzNjNjMjgxODkxIiwidXNlcl9pZCI6IjEifQ.KGmR_YxZG0t5szyU1LHuj-HOs_fNhyXgIxRDgd53sTI
Content-Type: application/json

{
"plan_name":"",
"plan_type":"",
"single_price":"",
"couple_price":"",
"group_price":"",
"description":"",
"upload_file":""
}


# ---------------------------------------MOBILE APPLICATON----------------------------------------------



### List plans by clients
GET {{base_url}}clientlist/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDIzODUyLCJpYXQiOjE3NjMzODA2NTIsImp0aSI6IjdhYzk0NTFmMGI1YzRmMjU4YTU3NTEyYjFhZGQ0MmVjIiwidXNlcl9pZCI6IjUifQ.qz6bPLLMhsRXTSv4egb4loALVGuibSKC4z0jSd5SZo4

### detail plan view for client
GET {{base_url}}clientview/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDIzODUyLCJpYXQiOjE3NjMzODA2NTIsImp0aSI6IjdhYzk0NTFmMGI1YzRmMjU4YTU3NTEyYjFhZGQ0MmVjIiwidXNlcl9pZCI6IjUifQ.qz6bPLLMhsRXTSv4egb4loALVGuibSKC4z0jSd5SZo4
