@base_url = http://127.0.0.1:8000/api/plan/

### Create plan
POST {{base_url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDAzNjQyLCJpYXQiOjE3NjMzNjA0NDIsImp0aSI6ImU2MjYwNWE0Y2U1MjQ2ZGQ4Mjc1YTkzNjNjMjgxODkxIiwidXNlcl9pZCI6IjEifQ.KGmR_YxZG0t5szyU1LHuj-HOs_fNhyXgIxRDgd53sTI
Content-Type: application/json

{
"plan_name":"",
"plan_type":"",
"single_price":"",
"couple_price":"",
"group_price":"",
"description":"",
"upload_file":""
}

### List all plan
GET {{base_url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTg0MzgzLCJpYXQiOjE3NjQxNDExODMsImp0aSI6IjBjMTNlNmNiMDRjZTQ5M2E4MDA3NDJjNmFhYjliNDI4IiwidXNlcl9pZCI6IjEifQ.4IeyO4KMyk-rXf8aTMil-XZxTnWmHIKS6mK91hhDzSM

### List all plan with pending trainer count
GET {{base_url}}pending-count/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTg0MzgzLCJpYXQiOjE3NjQxNDExODMsImp0aSI6IjBjMTNlNmNiMDRjZTQ5M2E4MDA3NDJjNmFhYjliNDI4IiwidXNlcl9pZCI6IjEifQ.4IeyO4KMyk-rXf8aTMil-XZxTnWmHIKS6mK91hhDzSM



### detail view by id
GET {{base_url}}1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDAzNjQyLCJpYXQiOjE3NjMzNjA0NDIsImp0aSI6ImU2MjYwNWE0Y2U1MjQ2ZGQ4Mjc1YTkzNjNjMjgxODkxIiwidXNlcl9pZCI6IjEifQ.KGmR_YxZG0t5szyU1LHuj-HOs_fNhyXgIxRDgd53sTI

### delete single plan
DELETE {{base_url}}1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDAzNjQyLCJpYXQiOjE3NjMzNjA0NDIsImp0aSI6ImU2MjYwNWE0Y2U1MjQ2ZGQ4Mjc1YTkzNjNjMjgxODkxIiwidXNlcl9pZCI6IjEifQ.KGmR_YxZG0t5szyU1LHuj-HOs_fNhyXgIxRDgd53sTI

### edit single plan
PUT {{base_url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDAzNjQyLCJpYXQiOjE3NjMzNjA0NDIsImp0aSI6ImU2MjYwNWE0Y2U1MjQ2ZGQ4Mjc1YTkzNjNjMjgxODkxIiwidXNlcl9pZCI6IjEifQ.KGmR_YxZG0t5szyU1LHuj-HOs_fNhyXgIxRDgd53sTI
Content-Type: application/json

{
"plan_name":"",
"plan_type":"",
"single_price":"",
"couple_price":"",
"group_price":"",
"description":"",
"upload_file":""
}


# ---------------------------------------MOBILE APPLICATON----------------------------------------------



### List plans by clients
GET {{base_url}}clientlist/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDIzODUyLCJpYXQiOjE3NjMzODA2NTIsImp0aSI6IjdhYzk0NTFmMGI1YzRmMjU4YTU3NTEyYjFhZGQ0MmVjIiwidXNlcl9pZCI6IjUifQ.qz6bPLLMhsRXTSv4egb4loALVGuibSKC4z0jSd5SZo4

### detail plan view for client
GET {{base_url}}clientview/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDIzODUyLCJpYXQiOjE3NjMzODA2NTIsImp0aSI6IjdhYzk0NTFmMGI1YzRmMjU4YTU3NTEyYjFhZGQ0MmVjIiwidXNlcl9pZCI6IjUifQ.qz6bPLLMhsRXTSv4egb4loALVGuibSKC4z0jSd5SZo4
