 @base_url = http://127.0.0.1:8000/api/section/

# @base_url = http://178.248.112.16:9001/api/section/

###----------------------login/get access token and refresh token for trainer
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "email_or_phno": "7025220037",
  "password": "Password@1234"
}


### session history by client id
GET {{base_url}}client/2/sessions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTc4NjE5LCJpYXQiOjE3NjU1MzU0MjAsImp0aSI6IjczMTI3NTNiZWI3YTQ4M2E4OGRiNGVjOTY5NjE1NDA0IiwidXNlcl9pZCI6IjEifQ.kwJW1GEtGN25RU5CU5vvv80BVn1_I4bKhWoLXAdVGM4
### session history by client id
GET {{base_url}}client/2/weekly-hours/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTc4NjE5LCJpYXQiOjE3NjU1MzU0MjAsImp0aSI6IjczMTI3NTNiZWI3YTQ4M2E4OGRiNGVjOTY5NjE1NDA0IiwidXNlcl9pZCI6IjEifQ.kwJW1GEtGN25RU5CU5vvv80BVn1_I4bKhWoLXAdVGM4
### todays sessions by trainer
GET {{base_url}}today-sessions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDkyNzczLCJpYXQiOjE3NjQwNDk1NzMsImp0aSI6IjQwNjc0NjkwMDBiMTQxMzNhMGQzYTE2ZWRjMTU1NDJjIiwidXNlcl9pZCI6IjQifQ.BCRwi1iQuXKstkSdWS2C8m7XDtOSo7K6-TsUFQc29MI



### client details by trainer
GET {{base_url}}client/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NDg5ODY4LCJpYXQiOjE3NjU0NDY2NjgsImp0aSI6ImMwNDMyYzAzODE1OTRmNzY5YmUxOWNlMWE5NGQ1MWExIiwidXNlcl9pZCI6IjEifQ.FlJe7yr_BFi_haGdDSFig047SGIo0IAQtaop_PN3pH0

### get all session details for trainer
GET {{base_url}}trainer/bookings/?date=2025-12-05
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDk1MTYzLCJpYXQiOjE3NjQwNTE5NjMsImp0aSI6ImJmOGE4ODJhMzBiMjRlY2FiZTVmZDE2MjY1ZGEwYTdiIiwidXNlcl9pZCI6IjQifQ.gzgAge--adSOOosRNODG4VO7wscJiwHnPys0C5AcD7o

### getting happend session details for trainer
GET {{base_url}}trainer/history/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDk1MTYzLCJpYXQiOjE3NjQwNTE5NjMsImp0aSI6ImJmOGE4ODJhMzBiMjRlY2FiZTVmZDE2MjY1ZGEwYTdiIiwidXNlcl9pZCI6IjQifQ.gzgAge--adSOOosRNODG4VO7wscJiwHnPys0C5AcD7o

### Start Training
POST {{base_url}}start-training/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTgwMjM4LCJpYXQiOjE3NjU1MzcwMzgsImp0aSI6IjUyZTEzMzRlMzRlYzRmMzliMjg5Mzk5NWFmZjkwZjM4IiwidXNlcl9pZCI6IjQifQ.60dyCE0U-KV7d9gCpXLGFLtiEKCIQdlBS0o2H1Ausro
Content-Type: application/json

{
    "booking_id": 5
}

### End Training
POST {{base_url}}end-training/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTgwMjM4LCJpYXQiOjE3NjU1MzcwMzgsImp0aSI6IjUyZTEzMzRlMzRlYzRmMzliMjg5Mzk5NWFmZjkwZjM4IiwidXNlcl9pZCI6IjQifQ.60dyCE0U-KV7d9gCpXLGFLtiEKCIQdlBS0o2H1Ausro
Content-Type: application/json

{
    "booking_id": 5
}


### client completed section list

GET {{base_url}}client/completed-sessions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDk5Mjc0LCJpYXQiOjE3NjQwNTYwNzQsImp0aSI6IjI1ZDRkMmMxM2JiMDQzYjJhOGUzNmJmZjc2NzVhZGMzIiwidXNlcl9pZCI6IjMifQ.FNEsEtAkv1Pk62SB_5yqC3JpeMk3FiUCWQjZRpL1FK0


### client completed section detail view
GET {{base_url}}client/completed-session/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDk5Mjc0LCJpYXQiOjE3NjQwNTYwNzQsImp0aSI6IjI1ZDRkMmMxM2JiMDQzYjJhOGUzNmJmZjc2NzVhZGMzIiwidXNlcl9pZCI6IjMifQ.FNEsEtAkv1Pk62SB_5yqC3JpeMk3FiUCWQjZRpL1FK0


### list trainer sessions
GET {{base_url}}admin/trainer/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTA0NDYzLCJpYXQiOjE3NjY0NjEyNjMsImp0aSI6IjA4NjlkMWRjYWM1MTQ3Zjk5ODk2YmIzZjZhZjE4MWQ1IiwidXNlcl9pZCI6IjEifQ.pq_Sv-ZSoI7BE6iu5rPhUFTXM9FRYZ6CQGT823xUCus


