### CLIENT: Create Ticket (Complaint)
POST http://178.248.112.16:9001/api/tickets/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzMDI2OTY1LCJpYXQiOjE3ODI5ODM3NjUsImp0aSI6IjFkYzc0NWE5ZjczZjQ0MDhhMTFjZjlmM2U5NjFhNWRjIiwidXNlcl9pZCI6IjMwOCJ9.3OFtpXkUM4h_jLek1w3o93E3McwxTGtTMr-6bfh26FU
Content-Type: application/json

{
    "trainer_id": 7,
    "complaint": "Trainer did not attend today's session."
}
### ADMIN: List Tickets
GET http://127.0.0.1:8000/api/tickets/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1OTIzOTYzLCJpYXQiOjE3NjU4ODA3NjMsImp0aSI6IjljMmEyMzVmYjkyYTRiNzY4ODI2YTA2MTBlZmY0MjBjIiwidXNlcl9pZCI6IjEifQ.LY6M8sFdml8A04_uaG2qDcbbBp9EO_CIiTfOEEj78Vg
### ADMIN: Ticket Detail View
GET http://127.0.0.1:8000/api/tickets/admin/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1OTIzOTYzLCJpYXQiOjE3NjU4ODA3NjMsImp0aSI6IjljMmEyMzVmYjkyYTRiNzY4ODI2YTA2MTBlZmY0MjBjIiwidXNlcl9pZCI6IjEifQ.LY6M8sFdml8A04_uaG2qDcbbBp9EO_CIiTfOEEj78Vg
### ADMIN: Update Ticket Status
PATCH http://127.0.0.1:8000/api/tickets/admin/1/status/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTc5MTE3LCJpYXQiOjE3NjQxMzU5MTcsImp0aSI6ImFlMDEwMWI4MTk4ODQxYjk5YjE0NjgzNGM2ZDcxOWZmIiwidXNlcl9pZCI6IjEifQ.KFoXyzoJFt0eS7oPuzDDqk1YpHA0v8R1Us_C4OlUhq4
Content-Type: application/json

{
  "status": "closed"
}

### ADMIN: List Tickets pending
GET http://127.0.0.1:8000/api/tickets/pending-request/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTA0NDYzLCJpYXQiOjE3NjY0NjEyNjMsImp0aSI6IjA4NjlkMWRjYWM1MTQ3Zjk5ODk2YmIzZjZhZjE4MWQ1IiwidXNlcl9pZCI6IjEifQ.pq_Sv-ZSoI7BE6iu5rPhUFTXM9FRYZ6CQGT823xUCus

