### CLIENT: Create Ticket (Complaint)
POST http://178.248.112.16:9001/api/tickets/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1OTE2MTgxLCJpYXQiOjE3NjU4NzI5ODEsImp0aSI6ImFmYmE2ZDc4ZWYyZTQ1NjNiNWQwYjQ2Yzg4OThmOGE0IiwidXNlcl9pZCI6IjE0In0.Ccu1Qnz5wkZosZxzTOQo7muxATJX3gD_N29b2BUBkKc
Content-Type: application/json

{
  "complaint": "Trainer is not responding properly during sessions."
}
### ADMIN: List Tickets
GET http://127.0.0.1:8000/api/tickets/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTc5MTE3LCJpYXQiOjE3NjQxMzU5MTcsImp0aSI6ImFlMDEwMWI4MTk4ODQxYjk5YjE0NjgzNGM2ZDcxOWZmIiwidXNlcl9pZCI6IjEifQ.KFoXyzoJFt0eS7oPuzDDqk1YpHA0v8R1Us_C4OlUhq4
### ADMIN: Ticket Detail View
GET http://127.0.0.1:8000/api/tickets/admin/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTc5MTE3LCJpYXQiOjE3NjQxMzU5MTcsImp0aSI6ImFlMDEwMWI4MTk4ODQxYjk5YjE0NjgzNGM2ZDcxOWZmIiwidXNlcl9pZCI6IjEifQ.KFoXyzoJFt0eS7oPuzDDqk1YpHA0v8R1Us_C4OlUhq4
### ADMIN: Update Ticket Status
PATCH http://127.0.0.1:8000/api/tickets/admin/1/status/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTc5MTE3LCJpYXQiOjE3NjQxMzU5MTcsImp0aSI6ImFlMDEwMWI4MTk4ODQxYjk5YjE0NjgzNGM2ZDcxOWZmIiwidXNlcl9pZCI6IjEifQ.KFoXyzoJFt0eS7oPuzDDqk1YpHA0v8R1Us_C4OlUhq4
Content-Type: application/json

{
  "status": "closed"
}
