    # @base_url = http://127.0.0.1:8000/api/trainer/
   @base_url = http://178.248.112.16:9001/api/trainer/

###----------------------login/get access token and refresh token
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "email_or_phno": "7025220037",
  "password": "Password@1234"
}

### Trainer Registration
POST {{base_url}}
Content-Type: application/json

{
  "name": "dummyyy",
  "phno": "4475656807",
  "email": "abcdfff@gmail.com",
  "dob": "2001-05-16",
  "training_field": 2,
  "section_timing": "30",
  "gender": "female",
  "location": "Kerala",
  "expecting_salary": "25000.00",
  "no_of_section": 3,
  "adar_number": "991882111100",
  "adar_image": "http://178.248.112.16:9001/media/certificates/97.jpg.webp",
  "password": "Password@1234",
  "certificates": [
    "http://178.248.112.16:9001/media/certificates/97.jpg.webp","http://178.248.112.16:9001/media/certificates/97.jpg.webp"
  ]
}



### Trainer List (Admin Only)
GET {{base_url}}list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTA0NDYzLCJpYXQiOjE3NjY0NjEyNjMsImp0aSI6IjA4NjlkMWRjYWM1MTQ3Zjk5ODk2YmIzZjZhZjE4MWQ1IiwidXNlcl9pZCI6IjEifQ.pq_Sv-ZSoI7BE6iu5rPhUFTXM9FRYZ6CQGT823xUCus


### Trainer Detail (Retrieve)
GET {{base_url}}29/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTgyMDAzLCJpYXQiOjE3NjYxMzg4MDMsImp0aSI6Ijg4MDZhOWYxMDNhMDQzODBhMzk2NTMwZDQ2NWYwNGM1IiwidXNlcl9pZCI6IjEifQ.dJkWMoIUCm22a8JBsWKQp62SgBOeuL6BQ64cZoUMeAQ




### Trainer Partial Update (PATCH)
PATCH {{base_url}}47/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MDI0ODAzLCJpYXQiOjE3NjY5ODE2MDMsImp0aSI6Ijk1MjhjMjQwNDZiYjQxNTRiYmY2N2YxOGQ3ZTQ5ZWM0IiwidXNlcl9pZCI6IjEifQ.VvYyB12I3S-HEGKgu5_I9z-Qnw97cPJ07_9jSQHgfac
Content-Type: application/json

{
  "status": "approved"
}




### Trainer Delete (Admin)
DELETE {{base_url}}1/
Authorization: Bearer <access_token>

# =================================================MOBILE APP==================================================

### Get Trainer Profile
GET {{base_url}}profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDg5ODA0LCJpYXQiOjE3NjQwNDY2MDQsImp0aSI6ImU3YTcwY2MyMDQ4NzQxYzA4NGMwYzQ3ODg5NWI1NDE3IiwidXNlcl9pZCI6IjUifQ.kGN2O8J-CCUwhk1jLNcqKHgnX59dhUGyltgrgO2jflo
Content-Type: application/json

### Edit Trainer Profile
PATCH {{base_url}}profile/edit/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDA4NDYwLCJpYXQiOjE3NjMzNjUyNjAsImp0aSI6Ijk3NjkyMDM4YjU5NTQ4NjliMjFiYmZkODE4ZWM5MTgyIiwidXNlcl9pZCI6IjQifQ.koPBJ1LU560FFaPOMZAUE7p1HJr7uQBUd8oR6NN8yI4
Content-Type: application/json

{
  "name": "jesna jamal"

}

### List Pending Trainers
GET {{base_url}}trainers/pending/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1OTk3MTA3LCJpYXQiOjE3NjU5NTM5MDcsImp0aSI6IjQ5M2E1YjBmNjE0MTRmMWViNDVmNmMwMmQ2ZDNkNzNlIiwidXNlcl9pZCI6IjEifQ.MyA2NICwvAOC0AyjP8ENjRO1uIRhxgrXCHTJoM3VrUI

### filter trainer by slot,time,date
POST {{base_url}}available-trainers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MDM4NDQ3LCJpYXQiOjE3NjY5OTUyNDcsImp0aSI6IjFhMTIwNWY2YmJhMDRjNWU4ZWU3MTIwMDE5YWVlNGFmIiwidXNlcl9pZCI6IjE1In0.OVcjhtd4-N7noNrI6I1i_7q-sf7O3e1V51aZRcmqxRA
Content-Type: application/json

{
  "plan_id": 2,
  "slot_days": ["mon", "wed", "fri"],
  "time": "12:00",
  "start_date": "2025-01-03"
}

### trainer detail view for modal in mobile app
GET {{base_url}}detail/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NjAzMjM1LCJpYXQiOjE3NjY1NjAwMzUsImp0aSI6IjFkYTEwNjY2ZTNmMzQxYWRiNzUyMmNiY2JiOTRiMzY0IiwidXNlcl9pZCI6IjIifQ.h_Ek10IsL7h-0J_IY_BidLAjV8s-CnTTvH_7wPSaDRk





### book filtered trainer
POST {{base_url}}book-trainer/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MDUyMjQzLCJpYXQiOjE3NjcwMDkwNDMsImp0aSI6IjhkYmEzZjFmNDE4ZjRjNzQ5YWUzZTBkZjEwMDMwMDlkIiwidXNlcl9pZCI6IjI2In0.6xL147Py47z-eegRMyC8G0xox9cSyHC9PPq_q6TmIIE
Content-Type: application/json

{
  "trainer_id": 66,
  "plan_id": 2,
  "start_date": "2025-12-29",
  "time": "18:00",
  "slot_days": ["mon", "wed", "fri"]  
}

### change trainer by user
GET {{base_url}}change/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDg1OTAyLCJpYXQiOjE3NjQwNDI3MDIsImp0aSI6IjYxYTZhMThlN2MxNDQ3NjE5N2E5ZGMyYjJlNzFkNTc3IiwidXNlcl9pZCI6IjMifQ.hb6GFjue_iPMinaQFs9EsaVsAI8sZRtYlwDbvJAL0p8


### get single trainer details using id
GET {{base_url}}info/10/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NjAzMjM1LCJpYXQiOjE3NjY1NjAwMzUsImp0aSI6IjFkYTEwNjY2ZTNmMzQxYWRiNzUyMmNiY2JiOTRiMzY0IiwidXNlcl9pZCI6IjIifQ.h_Ek10IsL7h-0J_IY_BidLAjV8s-CnTTvH_7wPSaDRk

### add notes on sessions by trainer
POST {{base_url}}booking/1/add-note/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTAxMTc2LCJpYXQiOjE3NjQwNTc5NzYsImp0aSI6IjM4YzFiYjVlZTA3NjQxZGJhZjM5Mzg3NDg2MmRiNmJlIiwidXNlcl9pZCI6IjQifQ.3O8V_ekbc7fHlGF4MVRpemyK0L46Qp7hAJTgbY1Om4U
Content-Type: application/json

{
    "note": "Client did well in today’s session."
}


### suspend trainer

POST {{base_url}}8/suspend/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTA0NDYzLCJpYXQiOjE3NjY0NjEyNjMsImp0aSI6IjA4NjlkMWRjYWM1MTQ3Zjk5ODk2YmIzZjZhZjE4MWQ1IiwidXNlcl9pZCI6IjEifQ.pq_Sv-ZSoI7BE6iu5rPhUFTXM9FRYZ6CQGT823xUCus



### pending trainer

GET {{base_url}}pending-request/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTA0NDYzLCJpYXQiOjE3NjY0NjEyNjMsImp0aSI6IjA4NjlkMWRjYWM1MTQ3Zjk5ODk2YmIzZjZhZjE4MWQ1IiwidXNlcl9pZCI6IjEifQ.pq_Sv-ZSoI7BE6iu5rPhUFTXM9FRYZ6CQGT823xUCus


