@base_url = http://127.0.0.1:8000/api/trainer/

###----------------------login/get access token and refresh token
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "email_or_phno": "7011126542",
  "password": "Password@1234"
}

### Trainer Registration
POST {{base_url}}
Content-Type: application/json

{
  "name": "ajay",
  "phno": "7944440837",
  "email": "ajay@gmail.com",
  "dob": "1994-05-16",
  "training_field": "4",
  "section_timing": "30",
  "gender": "male",
  "location": "Kerala",
  "expecting_salary": "25000.00",
  "no_of_section": 3,
  "adar_number": "999882320000",
  "adar_image": "http://127.0.0.1:8000/media/certificates/IDCARD.webp",
  "password": "Password@1234",
  "certificates": [
    "http://127.0.0.1:8000/media/certificates/IDCARD.webp","http://127.0.0.1:8000/media/certificates/IDCARD.webp"
  ]
}



### Trainer List (Admin Only)
GET {{base_url}}list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNTgxNDI4LCJpYXQiOjE3NjM1MzgyMjgsImp0aSI6ImYwZjZhZTM1ZDJlMjQ0NjM5OGFlZGEzNWM0YTBiMzgwIiwidXNlcl9pZCI6IjEifQ.bcBCxHK8dn-3XgabaUqM_IaBc9wWDigI36hmFNcML3Y


### Trainer Detail (Retrieve)
GET {{base_url}}9/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMzUyMzQxLCJpYXQiOjE3NjMzNTIwNDEsImp0aSI6IjFjN2YxNGVjZjUwOTRiZDE4ZjA3M2FjOTNmY2EwNjQ2IiwidXNlcl9pZCI6IjEifQ.ACij0LlKUKok5njkbs2jj9aAV386lW3jurneqK9ir5w




### Trainer Partial Update (PATCH)
PATCH {{base_url}}19/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDk0OTkyLCJpYXQiOjE3NjM0NTE3OTIsImp0aSI6IjJlNWFiY2Q3ZmVmZTRmOTI4NzI4MDg1MDgwZmRmN2QzIiwidXNlcl9pZCI6IjEifQ.UaQ36OF1dAbclFNbiLCLvsIt44vuy2rCUKKNJG66WRI
Content-Type: application/json

{
  "status": "approved"
}




### Trainer Delete (Admin)
DELETE {{base_url}}1/
Authorization: Bearer <access_token>

# =================================================MOBILE APP==================================================

### Get Trainer Profile
GET {{base_url}}profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDA4NDYwLCJpYXQiOjE3NjMzNjUyNjAsImp0aSI6Ijk3NjkyMDM4YjU5NTQ4NjliMjFiYmZkODE4ZWM5MTgyIiwidXNlcl9pZCI6IjQifQ.koPBJ1LU560FFaPOMZAUE7p1HJr7uQBUd8oR6NN8yI4
Content-Type: application/json

### Edit Trainer Profile
PATCH {{base_url}}profile/edit/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDA4NDYwLCJpYXQiOjE3NjMzNjUyNjAsImp0aSI6Ijk3NjkyMDM4YjU5NTQ4NjliMjFiYmZkODE4ZWM5MTgyIiwidXNlcl9pZCI6IjQifQ.koPBJ1LU560FFaPOMZAUE7p1HJr7uQBUd8oR6NN8yI4
Content-Type: application/json

{
  "name": "jesna jamal"

}

### List Pending Trainers
GET {{base_url}}trainers/pending/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDA5ODUxLCJpYXQiOjE3NjMzNjY2NTEsImp0aSI6IjhkNDBmNWY3MDc3ZDRhMDA5ZjIwYzVlYTMwYTNmYjc4IiwidXNlcl9pZCI6IjEifQ.vQkS6wLWkCnBhsY3t91sTv6YiJeAytmQZ1mE-oOtH9A

### filter trainer by slot,time,date
POST {{base_url}}available-trainers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNTgyNTQ3LCJpYXQiOjE3NjM1MzkzNDcsImp0aSI6IjhhN2Y2ODkwYTE3NzQxMDdhYTRlNzgxMzVhYjQ2MWRlIiwidXNlcl9pZCI6IjEwIn0.8F-JVCdr7X-mx7deL_Py6HCBLkeGqNn_Sia0PKFxFYQ
Content-Type: application/json

{
  "plan_id": 5,
  "slot_days": ["mon", "wed", "fri"],
  "time": "11:00",
  "start_date": "2025-11-19"
}

### filter trainer by slot,time,date
POST {{base_url}}book-trainer/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNTgyNTQ3LCJpYXQiOjE3NjM1MzkzNDcsImp0aSI6IjhhN2Y2ODkwYTE3NzQxMDdhYTRlNzgxMzVhYjQ2MWRlIiwidXNlcl9pZCI6IjEwIn0.8F-JVCdr7X-mx7deL_Py6HCBLkeGqNn_Sia0PKFxFYQ
Content-Type: application/json

{
  "trainer_id": 16,
  "plan_id": 5,
  "start_date": "2025-11-19",
  "time": "10:00",
  "slot_days": ["mon", "wed", "fri"]  
}
